
import NFT_1 from '../assets/images/nft_1.png'
import NFT_2 from '../assets/images/nft_2.png'
import NFT_3 from '../assets/images/nft_3.png'
import NFT_4 from '../assets/images/nft_4.png'
import NFT_5 from '../assets/images/nft_5.png'
import NFT_6 from '../assets/images/nft_6.png'
import NFT_7 from '../assets/images/nft_7.png'
import NFT_8 from '../assets/images/nft_8.png'
import NftGrid from '../layouts/NftGrid'

const datas = [
    {
        id: 135123,
        price: 1.3,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_1,
        owner: '',
    },
    {
        id: 135124,
        price: 1.5,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_2,
        owner: '',
    },
    {
        id: 135125,
        price: 2.1,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_3,
        owner: '',
    },
    {
        id: 135126,
        price: 7.1,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_4,
        owner: '',
    },
    {
        id: 135127,
        price: 2.9,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_5,
        owner: '',
    },
    {
        id: 135128,
        price: 5.0,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_6,
        owner: '',
    },
    {
        id: 135129,
        price: 1.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_7,
        owner: '',
    },
    {
        id: 135130,
        price: 0.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_8,
        owner: '',
    },
    {
        id: 135130,
        price: 0.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_8,
        owner: '',
    },
    {
        id: 135123,
        price: 1.3,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_1,
        owner: '',
    },
    {
        id: 135124,
        price: 1.5,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_2,
        owner: '',
    },
    {
        id: 135125,
        price: 2.1,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_3,
        owner: '',
    },
    {
        id: 135126,
        price: 7.1,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_4,
        owner: '',
    },
    {
        id: 135127,
        price: 2.9,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_5,
        owner: '',
    },
    {
        id: 135128,
        price: 5.0,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_6,
        owner: '',
    },
    {
        id: 135129,
        price: 1.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_7,
        owner: '',
    },
    {
        id: 135130,
        price: 0.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_8,
        owner: '',
    },
    {
        id: 135130,
        price: 0.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_8,
        owner: '',
    },
    {
        id: 135123,
        price: 1.3,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_1,
        owner: '',
    },
    {
        id: 135124,
        price: 1.5,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_2,
        owner: '',
    },
    {
        id: 135125,
        price: 2.1,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_3,
        owner: '',
    },
    {
        id: 135126,
        price: 7.1,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_4,
        owner: '',
    },
    {
        id: 135127,
        price: 2.9,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_5,
        owner: '',
    },
    {
        id: 135128,
        price: 5.0,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_6,
        owner: '',
    },
    {
        id: 135129,
        price: 1.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_7,
        owner: '',
    },
    {
        id: 135130,
        price: 0.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_8,
        owner: '',
    },
    {
        id: 135130,
        price: 0.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_8,
        owner: '',
    },
    {
        id: 135123,
        price: 1.3,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_1,
        owner: '',
    },
    {
        id: 135124,
        price: 1.5,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_2,
        owner: '',
    },
    {
        id: 135125,
        price: 2.1,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_3,
        owner: '',
    },
    {
        id: 135126,
        price: 7.1,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_4,
        owner: '',
    },
    {
        id: 135127,
        price: 2.9,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_5,
        owner: '',
    },
    {
        id: 135128,
        price: 5.0,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_6,
        owner: '',
    },
    {
        id: 135129,
        price: 1.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_7,
        owner: '',
    },
    {
        id: 135130,
        price: 0.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_8,
        owner: '',
    },
    {
        id: 135130,
        price: 0.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_8,
        owner: '',
    },
    {
        id: 135123,
        price: 1.3,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_1,
        owner: '',
    },
    {
        id: 135124,
        price: 1.5,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_2,
        owner: '',
    },
    {
        id: 135125,
        price: 2.1,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_3,
        owner: '',
    },
    {
        id: 135126,
        price: 7.1,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_4,
        owner: '',
    },
    {
        id: 135127,
        price: 2.9,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_5,
        owner: '',
    },
    {
        id: 135128,
        price: 5.0,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_6,
        owner: '',
    },
    {
        id: 135129,
        price: 1.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_7,
        owner: '',
    },
    {
        id: 135130,
        price: 0.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_8,
        owner: '',
    },
    {
        id: 135130,
        price: 0.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_8,
        owner: '',
    },
    {
        id: 135123,
        price: 1.3,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_1,
        owner: '',
    },
    {
        id: 135124,
        price: 1.5,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_2,
        owner: '',
    },
    {
        id: 135125,
        price: 2.1,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_3,
        owner: '',
    },
    {
        id: 135126,
        price: 7.1,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_4,
        owner: '',
    },
    {
        id: 135127,
        price: 2.9,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_5,
        owner: '',
    },
    {
        id: 135128,
        price: 5.0,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_6,
        owner: '',
    },
    {
        id: 135129,
        price: 1.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_7,
        owner: '',
    },
    {
        id: 135130,
        price: 0.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_8,
        owner: '',
    },
    {
        id: 135130,
        price: 0.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_8,
        owner: '',
    },
    {
        id: 135123,
        price: 1.3,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_1,
        owner: '',
    },
    {
        id: 135124,
        price: 1.5,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_2,
        owner: '',
    },
    {
        id: 135125,
        price: 2.1,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_3,
        owner: '',
    },
    {
        id: 135126,
        price: 7.1,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_4,
        owner: '',
    },
    {
        id: 135127,
        price: 2.9,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_5,
        owner: '',
    },
    {
        id: 135128,
        price: 5.0,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_6,
        owner: '',
    },
    {
        id: 135129,
        price: 1.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_7,
        owner: '',
    },
    {
        id: 135130,
        price: 0.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_8,
        owner: '',
    },
    {
        id: 135130,
        price: 0.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_8,
        owner: '',
    },
    {
        id: 135123,
        price: 1.3,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_1,
        owner: '',
    },
    {
        id: 135124,
        price: 1.5,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_2,
        owner: '',
    },
    {
        id: 135125,
        price: 2.1,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_3,
        owner: '',
    },
    {
        id: 135126,
        price: 7.1,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_4,
        owner: '',
    },
    {
        id: 135127,
        price: 2.9,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_5,
        owner: '',
    },
    {
        id: 135128,
        price: 5.0,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_6,
        owner: '',
    },
    {
        id: 135129,
        price: 1.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_7,
        owner: '',
    },
    {
        id: 135130,
        price: 0.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_8,
        owner: '',
    },
    {
        id: 135130,
        price: 0.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_8,
        owner: '',
    },
    {
        id: 135123,
        price: 1.3,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_1,
        owner: '',
    },
    {
        id: 135124,
        price: 1.5,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_2,
        owner: '',
    },
    {
        id: 135125,
        price: 2.1,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_3,
        owner: '',
    },
    {
        id: 135126,
        price: 7.1,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_4,
        owner: '',
    },
    {
        id: 135127,
        price: 2.9,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_5,
        owner: '',
    },
    {
        id: 135128,
        price: 5.0,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_6,
        owner: '',
    },
    {
        id: 135129,
        price: 1.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_7,
        owner: '',
    },
    {
        id: 135130,
        price: 0.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_8,
        owner: '',
    },
    {
        id: 135130,
        price: 0.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_8,
        owner: '',
    },
    {
        id: 135123,
        price: 1.3,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_1,
        owner: '',
    },
    {
        id: 135124,
        price: 1.5,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_2,
        owner: '',
    },
    {
        id: 135125,
        price: 2.1,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_3,
        owner: '',
    },
    {
        id: 135126,
        price: 7.1,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_4,
        owner: '',
    },
    {
        id: 135127,
        price: 2.9,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_5,
        owner: '',
    },
    {
        id: 135128,
        price: 5.0,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_6,
        owner: '',
    },
    {
        id: 135129,
        price: 1.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_7,
        owner: '',
    },
    {
        id: 135130,
        price: 0.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_8,
        owner: '',
    },
    {
        id: 135130,
        price: 0.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_8,
        owner: '',
    },
    {
        id: 135123,
        price: 1.3,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_1,
        owner: '',
    },
    {
        id: 135124,
        price: 1.5,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_2,
        owner: '',
    },
    {
        id: 135125,
        price: 2.1,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_3,
        owner: '',
    },
    {
        id: 135126,
        price: 7.1,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_4,
        owner: '',
    },
    {
        id: 135127,
        price: 2.9,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_5,
        owner: '',
    },
    {
        id: 135128,
        price: 5.0,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_6,
        owner: '',
    },
    {
        id: 135129,
        price: 1.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_7,
        owner: '',
    },
    {
        id: 135130,
        price: 0.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_8,
        owner: '',
    },
    {
        id: 135130,
        price: 0.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_8,
        owner: '',
    },
    {
        id: 135123,
        price: 1.3,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_1,
        owner: '',
    },
    {
        id: 135124,
        price: 1.5,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_2,
        owner: '',
    },
    {
        id: 135125,
        price: 2.1,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_3,
        owner: '',
    },
    {
        id: 135126,
        price: 7.1,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_4,
        owner: '',
    },
    {
        id: 135127,
        price: 2.9,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_5,
        owner: '',
    },
    {
        id: 135128,
        price: 5.0,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_6,
        owner: '',
    },
    {
        id: 135129,
        price: 1.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_7,
        owner: '',
    },
    {
        id: 135130,
        price: 0.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_8,
        owner: '',
    },
    {
        id: 135130,
        price: 0.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_8,
        owner: '',
    },
    {
        id: 135123,
        price: 1.3,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_1,
        owner: '',
    },
    {
        id: 135124,
        price: 1.5,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_2,
        owner: '',
    },
    {
        id: 135125,
        price: 2.1,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_3,
        owner: '',
    },
    {
        id: 135126,
        price: 7.1,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_4,
        owner: '',
    },
    {
        id: 135127,
        price: 2.9,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_5,
        owner: '',
    },
    {
        id: 135128,
        price: 5.0,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_6,
        owner: '',
    },
    {
        id: 135129,
        price: 1.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_7,
        owner: '',
    },
    {
        id: 135130,
        price: 0.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_8,
        owner: '',
    },
    {
        id: 135130,
        price: 0.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_8,
        owner: '',
    },
    {
        id: 135123,
        price: 1.3,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_1,
        owner: '',
    },
    {
        id: 135124,
        price: 1.5,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_2,
        owner: '',
    },
    {
        id: 135125,
        price: 2.1,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_3,
        owner: '',
    },
    {
        id: 135126,
        price: 7.1,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_4,
        owner: '',
    },
    {
        id: 135127,
        price: 2.9,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_5,
        owner: '',
    },
    {
        id: 135128,
        price: 5.0,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_6,
        owner: '',
    },
    {
        id: 135129,
        price: 1.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_7,
        owner: '',
    },
    {
        id: 135130,
        price: 0.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_8,
        owner: '',
    },
    {
        id: 135130,
        price: 0.8,
        name: "Private's Helmet",
        head: 3,
        body: 21,
        arm: 4,
        special: 7,
        nft: NFT_8,
        owner: '',
    }
];

function Marketplace() {
    return (
        <>
            <div className='mt-20 px-4 lg:px-24'>
                <h1 className='text-white text-[42px] font-bold '>Marketplace</h1>
                <div className='w-full flex justify-center items-center mx-auto'>
                    <NftGrid datas={datas} />
                </div>
            </div>
        </>);
}

export default Marketplace;